[package]
name = "thread-city"
version = "0.1.0"
edition = "2024"

[dependencies]
mypthreads = { path = "../mypthreads" }
rand = "0.10.0-rc.0"

gtk = { package = "gtk4", version = ">=0.7", features = ["v4_10"] }
glib = "0.17"
